/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* capsense_ISR */
#define capsense_ISR__INTC_CORTEXM4_ASSIGNED 1
#define capsense_ISR__INTC_CORTEXM4_PRIORITY 7u
#define capsense_ISR__INTC_NUMBER 49u
#define capsense_ISR_INTC_CORTEXM4_ASSIGNED 1
#define capsense_ISR_INTC_CORTEXM4_PRIORITY 7u
#define capsense_ISR_INTC_NUMBER 49u

/* ble_bless_isr */
#define ble_bless_isr__INTC_CORTEXM4_ASSIGNED 1
#define ble_bless_isr__INTC_CORTEXM4_PRIORITY 7u
#define ble_bless_isr__INTC_NUMBER 24u
#define ble_bless_isr_INTC_CORTEXM4_ASSIGNED 1
#define ble_bless_isr_INTC_CORTEXM4_PRIORITY 7u
#define ble_bless_isr_INTC_NUMBER 24u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
