/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* red */
#define red_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define red_0_INBUF_ENABLED 0u
#define red_0_INIT_DRIVESTATE 0u
#define red_0_INIT_MUXSEL 0u
#define red_0_INPUT_SYNC 2u
#define red_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define red_0_NUM 3u
#define red_0_PORT GPIO_PRT0
#define red_0_SLEWRATE CY_GPIO_SLEW_FAST
#define red_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define red_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define red_INBUF_ENABLED 0u
#define red_INIT_DRIVESTATE 0u
#define red_INIT_MUXSEL 0u
#define red_INPUT_SYNC 2u
#define red_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define red_NUM 3u
#define red_PORT GPIO_PRT0
#define red_SLEWRATE CY_GPIO_SLEW_FAST
#define red_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* blue */
#define blue_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define blue_0_INBUF_ENABLED 0u
#define blue_0_INIT_DRIVESTATE 1u
#define blue_0_INIT_MUXSEL 3u
#define blue_0_INPUT_SYNC 2u
#define blue_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define blue_0_NUM 1u
#define blue_0_PORT GPIO_PRT11
#define blue_0_SLEWRATE CY_GPIO_SLEW_FAST
#define blue_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define blue_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define blue_INBUF_ENABLED 0u
#define blue_INIT_DRIVESTATE 1u
#define blue_INIT_MUXSEL 3u
#define blue_INPUT_SYNC 2u
#define blue_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define blue_NUM 1u
#define blue_PORT GPIO_PRT11
#define blue_SLEWRATE CY_GPIO_SLEW_FAST
#define blue_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* capsense_Sns */
#define capsense_Sns_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define capsense_Sns_0_INBUF_ENABLED 0u
#define capsense_Sns_0_INIT_DRIVESTATE 1u
#define capsense_Sns_0_INIT_MUXSEL 0u
#define capsense_Sns_0_INPUT_SYNC 2u
#define capsense_Sns_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define capsense_Sns_0_NUM 3u
#define capsense_Sns_0_PORT GPIO_PRT8
#define capsense_Sns_0_SLEWRATE CY_GPIO_SLEW_FAST
#define capsense_Sns_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define capsense_Sns_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define capsense_Sns_1_INBUF_ENABLED 0u
#define capsense_Sns_1_INIT_DRIVESTATE 1u
#define capsense_Sns_1_INIT_MUXSEL 0u
#define capsense_Sns_1_INPUT_SYNC 2u
#define capsense_Sns_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define capsense_Sns_1_NUM 4u
#define capsense_Sns_1_PORT GPIO_PRT8
#define capsense_Sns_1_SLEWRATE CY_GPIO_SLEW_FAST
#define capsense_Sns_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define capsense_Sns_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define capsense_Sns_2_INBUF_ENABLED 0u
#define capsense_Sns_2_INIT_DRIVESTATE 1u
#define capsense_Sns_2_INIT_MUXSEL 0u
#define capsense_Sns_2_INPUT_SYNC 2u
#define capsense_Sns_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define capsense_Sns_2_NUM 5u
#define capsense_Sns_2_PORT GPIO_PRT8
#define capsense_Sns_2_SLEWRATE CY_GPIO_SLEW_FAST
#define capsense_Sns_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define capsense_Sns_3_DRIVEMODE CY_GPIO_DM_ANALOG
#define capsense_Sns_3_INBUF_ENABLED 0u
#define capsense_Sns_3_INIT_DRIVESTATE 1u
#define capsense_Sns_3_INIT_MUXSEL 0u
#define capsense_Sns_3_INPUT_SYNC 2u
#define capsense_Sns_3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define capsense_Sns_3_NUM 6u
#define capsense_Sns_3_PORT GPIO_PRT8
#define capsense_Sns_3_SLEWRATE CY_GPIO_SLEW_FAST
#define capsense_Sns_3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define capsense_Sns_4_DRIVEMODE CY_GPIO_DM_ANALOG
#define capsense_Sns_4_INBUF_ENABLED 0u
#define capsense_Sns_4_INIT_DRIVESTATE 1u
#define capsense_Sns_4_INIT_MUXSEL 0u
#define capsense_Sns_4_INPUT_SYNC 2u
#define capsense_Sns_4_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define capsense_Sns_4_NUM 7u
#define capsense_Sns_4_PORT GPIO_PRT8
#define capsense_Sns_4_SLEWRATE CY_GPIO_SLEW_FAST
#define capsense_Sns_4_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* capsense_Cmod */
#define capsense_Cmod_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define capsense_Cmod_0_INBUF_ENABLED 0u
#define capsense_Cmod_0_INIT_DRIVESTATE 1u
#define capsense_Cmod_0_INIT_MUXSEL 0u
#define capsense_Cmod_0_INPUT_SYNC 2u
#define capsense_Cmod_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define capsense_Cmod_0_NUM 7u
#define capsense_Cmod_0_PORT GPIO_PRT7
#define capsense_Cmod_0_SLEWRATE CY_GPIO_SLEW_FAST
#define capsense_Cmod_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define capsense_Cmod_DRIVEMODE CY_GPIO_DM_ANALOG
#define capsense_Cmod_INBUF_ENABLED 0u
#define capsense_Cmod_INIT_DRIVESTATE 1u
#define capsense_Cmod_INIT_MUXSEL 0u
#define capsense_Cmod_INPUT_SYNC 2u
#define capsense_Cmod_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define capsense_Cmod_NUM 7u
#define capsense_Cmod_PORT GPIO_PRT7
#define capsense_Cmod_SLEWRATE CY_GPIO_SLEW_FAST
#define capsense_Cmod_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
